### ISSUE TITLE
Error executing job with overrides:

### ISSUE THREAD

**Issue by dong-menghao** [ml-jku/L2M#1]
hello! When I perform pre-training,some errors were found as shown follows:

Error executing job with overrides: ['experiment_name=pretrain', 'seed=43', 'env_params=multi_domain_mtdmc', 'run_params=pretrain', 'eval_params=pretrain_disc', 'agent_params=cdt_pretrain_disc', 'agent_params.kind=MDDT', 'agent_params/model_kwargs=multi_domain_mtdmc', 'agent_params/data_paths=mt40v2_dmc10', '+agent_params/replay_buffer_kwargs=multi_domain_mtdmc', '+agent_params.accumulation_steps=2']
Traceback (most recent call last):
  File "/home/dong/py_projects/L2M/main.py", line 185, in main
    env, eval_env = make_env(config, logdir)
  File "/home/dong/py_projects/L2M/src/envs/builder.py", line 164, in make_env
    env = DummyVecEnv(get_cw_env_constructors(env_params.envid, randomization=env_params.randomization,
  File "/home/dong/anaconda3/envs/mddt/lib/python3.9/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 25, in __init__
    self.envs = [fn() for fn in env_fns]
  File "/home/dong/anaconda3/envs/mddt/lib/python3.9/site-packages/stable_baselines3/common/vec_env/dummy_vec_env.py", line 25, in <listcomp>
    self.envs = [fn() for fn in env_fns]
  File "/home/dong/py_projects/L2M/src/envs/cw_utils.py", line 146, in make
    return Monitor(get_single_env(task, one_hot_idx=one_hot_idx, one_hot_len=one_hot_len,
  File "/home/dong/py_projects/L2M/src/envs/cw_utils.py", line 41, in get_single_env
    env = MT50.train_classes[task_name]()
KeyError: 'reach-v2'

**Comment by thomasschmied** [comment]
Hi, thanks for trying out the repo!

It seems like you have v1 of `meta-world`  installed, as `reach-v2` is not detected. Did you follow the installation instructions in the [README](https://github.com/ml-jku/L2M#installation)? Try installing v2 of `meta-world` using: 
```
pip install git+https://github.com/rlworkgroup/metaworld.git@18118a28c06893da0f363786696cc792457b062b
```
Let me know if that worked for you :-)

**Comment by dong-menghao** [comment]
> Hi, thanks for trying out the repo!
> 
> It seems like you have v1 of `meta-world` installed, as `reach-v2` is not detected. Did you follow the installation instructions in the [README](https://github.com/ml-jku/L2M#installation)? Try installing v2 of `meta-world` using:
> 
> ```
> pip install git+https://github.com/rlworkgroup/metaworld.git@18118a28c06893da0f363786696cc792457b062b
> ```
> 
> Let me know if that worked for you :-)

yes,it works.
but because of my network,I use 
`git clone https://github.com/Farama-Foundation/Metaworld.git
`
`pip install -e .`

thanks for your help!!
