### ISSUE TITLE
pip install git+https://github.com/rlworkgroup/metaworld.git@18118a28c06893da0f363786696cc792457b062b

### ISSUE THREAD

**Issue by kkq2018** [ml-jku/L2M#2]
I can't pip install git+https://github.com/rlworkgroup/metaworld.git@18118a28c06893da0f363786696cc792457b062b.It seems https://github.com/rlworkgroup/metaworld.git@18118a28c06893da0f363786696cc792457b062b invalid

**Comment by thomasschmied** [comment]
Hi, thanks for trying the repo! 

Interesting, for me the installation still works. However, it seems Meta-World has recently been moved to a new [location](https://github.com/Farama-Foundation/Metaworld). 

You can try the following installation command instead, which should also work:
```
pip install git+https://github.com/Farama-Foundation/Metaworld.git@18118a28c06893da0f363786696cc792457b062b
```
Let me know if that worked for you :-)
