### ISSUE TITLE
Continualworld with Meta World V2

### ISSUE THREAD

**Issue by chufanchen** [ml-jku/L2M#4]
After following the instruction of installation, when I run `python main.py -m experiment_name=pretrain seed=42,43,44 env_params=multi_domain_mtdmc run_params=pretrain eval_params=pretrain_disc agent_params=cdt_pretrain_disc agent_params.kind=MDDT agent_params/model_kwargs=multi_domain_mtdmc agent_params/data_paths=mt40v2_dmc10 +agent_params/replay_buffer_kwargs=multi_domain_mtdmc +agent_params.accumulation_steps=2`.

The error occurs:
```
    env = MT50.train_classes[task_name]()
KeyError: 'reach-v2'
```

It seems like the continualworld（https://github.com/awarelab/continual_world/blob/73f63bb4fa0b5d00bda973e20dfb783bfcf1b8aa/continualworld/tasks.py） only use meta world v1.

**Comment by thomasschmied** [comment]
Excuse the late response. Yes, Continual-World used Meta-World v1 by default. To get v2 of Meta-World, you need to install it as described in the [installation ](https://github.com/ml-jku/L2M?tab=readme-ov-file#installation) instructions:
```
pip install git+https://github.com/rlworkgroup/metaworld.git@18118a28c06893da0f363786696cc792457b062b
```
Afterwards the import should work. You can also refer to [issue1 ](https://github.com/ml-jku/L2M/issues/1) and [issue2](https://github.com/ml-jku/L2M/issues/2).

I hope this helps!
